const data = [
  { id: 0, value: 'zero', title: 'Выберите размерность' },
  { id: 1, value: 'г/л', title: 'г/л' },
  { id: 2, value: '10*9/л', title: '10*9/л' },
  { id: 3, value: '10*121/л', title: '10*121/л' },
  { id: 4, value: 'мм/ч', title: 'мм/ч' },
  { id: 5, value: 'пг/кл', title: 'пг/кл' },
  { id: 6, value: 'мм/час', title: 'мм/час' },
  { id: 7, value: 'фл', title: 'фл' },
  { id: 8, value: 'пг', title: 'пг' },
  { id: 9, value: 'г/дл', title: 'г/дл' },
  { id: 10, value: '10*12/л', title: '10*12/л' },
  { id: 11, value: 'абс. кол-во', title: 'абс. кол-во' },
  { id: 12, value: 'отн. кол-во', title: 'отн. кол-во' },
  { id: 13, value: '10*3/мкл', title: '10*3/мкл' },
  { id: 14, value: 'промиле', title: 'промиле' },
  { id: 15, value: 'г/%', title: 'г/%' },
  { id: 16, value: 'кл/100 лейк.', title: 'кл/100 лейк.' },
  { id: 17, value: 'тыс/мкл', title: 'тыс/мкл' },
  { id: 18, value: 'полуколичественно в+', title: 'полуколичественно в+' },
  { id: 19, value: 'фемтолитр', title: 'фемтолитр' },
  { id: 20, value: '% к числу эритроцитов', title: '% к числу эритроцитов' },
]